import React, { useRef, useState, useSyncExternalStore } from "react";
import type { ReactNode } from "react";
import { Button, Modal } from "@deepseek-ai/dsh-client-ui-primitives";
import type { Channel } from "../domain/primitives.ts";
import type { BatchPreflightResult } from "../domain/batchPreflight.ts";
import type { ContentLibraryController, ContentLibraryState } from "./content-library-controller.ts";
import { publicationChannelLabel } from "./publication.tsx";
import { useDialogFocus } from "./interactions.ts";
import { workbenchStyles } from "./styles.ts";

const channels: Channel[] = ["wechat", "zhihu", "xiaohongshu", "x"];
export const contentBatchStyles = `
.wm-content-itemrow{display:flex;align-items:center;gap:2px;flex:none;min-width:0}.wm-content-itemrow>.wm-content-item{flex:1;min-width:0}.wm-content-itemcheck{width:14px;height:14px;flex:none;margin:0 1px 0 0;accent-color:var(--wcl-accent)}.wm-content-batchbar{display:flex;align-items:center;gap:6px;border-top:1px solid var(--wcl-border);padding:8px 2px 0;flex:none;font-size:10px;color:var(--wcl-muted)}.wm-content-batchbar button{font-size:11px}.wm-content-batchbar>span{margin-right:auto}.wm-batch-dialog{width:min(840px,calc(100vw - 24px));max-height:90vh}.wm-batch-channels{display:flex;gap:14px;flex-wrap:wrap}.wm-batch-channels label{display:flex;align-items:center;gap:5px}.wm-batch-channels input{width:auto}.wm-batch-results{display:flex;flex-direction:column;gap:10px;max-height:45vh;overflow:auto}.wm-batch-result{border:1px solid var(--wm-border);padding:12px;border-radius:8px;display:flex;flex-direction:column;gap:6px}.wm-batch-result h4{margin:0;font-size:12px;overflow-wrap:anywhere}.wm-batch-result[data-status=block]{border-left:3px solid var(--dsw-alias-label-error,var(--wm-muted))}.wm-batch-result p{font-size:12px;line-height:1.7;overflow-wrap:anywhere}.wm-batch-result details{font-size:11px;overflow-wrap:anywhere}.wm-batch-selection{max-height:100px;overflow:auto;font-size:12px;line-height:1.7}
`;

export function ContentBatchResults({ result, checked }: { result: BatchPreflightResult; checked: ContentLibraryState["checked"] }): ReactNode {
  return <><p className="wm-small wm-muted">{result.cancelled ? "本次检查已取消，以下为已返回结果。" : "只读检查已完成。"} 检查时间：{Number.isFinite(Date.parse(result.checkedAt)) ? new Date(result.checkedAt).toLocaleString("zh-CN") : "未记录"}</p><div className="wm-batch-results" aria-label="逐内容逐渠道检查结果">{result.results.map((entry, index) => <section key={`${entry.contentRef}:${entry.channel}:${index}`} className="wm-batch-result" data-status={entry.status}><div className="wm-row wm-between"><h4>{checked.find(value => value.contentRef === entry.contentRef)?.title ?? "所选内容"} · {publicationChannelLabel(entry.channel)}</h4><span className="wm-pill">{{ pass: "通过", warn: "需留意", block: "未就绪" }[entry.status]}</span></div><p>{entry.safeMessage}</p>{entry.issues.length > 0 && <ul className="wm-small">{entry.issues.map((issue, position) => <li key={position}>{issue}</li>)}</ul>}<details><summary>检查依据</summary><p>{entry.code}{entry.revisionDigest ? ` · ${entry.revisionDigest}` : " · 版本不可用"}</p></details></section>)}</div>{!result.results.length && <p>本次没有返回可展示的检查结果。</p>}</>;
}

export function ContentBatchBar({ controller }: { controller: ContentLibraryController }): ReactNode {
  const state = useSyncExternalStore(controller.subscribe, controller.getSnapshot, controller.getSnapshot);
  const [open, setOpen] = useState(false), [cancelled, setCancelled] = useState(false);
  const ref = useRef<HTMLDivElement>(null); useDialogFocus(ref, open);
  if (!state.checked.length) return null;
  const close = () => { controller.cancelBatch(); setOpen(false); };
  return <><div className="wm-content-batchbar"><span>已选 {state.checked.length} / 20</span><Button size="sm" variant="toolbar" onClick={() => { setCancelled(false); setOpen(true); }}>批量预检</Button><button type="button" className="wm-content-clearfilters" style={{ position: "static" }} onClick={() => { close(); controller.clearChecked(); }}>清除勾选</button></div><Modal open={open} title="只读批量检查" onClose={close} closeLabel="关闭批量检查" className="wm-workbench wm-batch-dialog" footer={<>{state.batchLoading ? <Button onClick={() => { controller.cancelBatch(); setCancelled(true); }}>取消检查</Button> : <Button variant="primary" disabled={!state.connected || !state.batchChannels.length} onClick={() => { setCancelled(false); void controller.runBatchPreflight(); }}>{state.batchResult ? "重新检查" : "开始只读检查"}</Button>}</>}><style>{workbenchStyles}{contentBatchStyles}</style><div ref={ref} tabIndex={-1} className="wm-stack"><p>检查 {state.checked.length} 份已保存内容的渠道准备状态。</p><details><summary>已勾选内容</summary><ul className="wm-batch-selection">{state.checked.map(value => <li key={value.contentRef}>{value.title}</li>)}</ul></details><div className="wm-batch-channels" role="group" aria-label="批量检查渠道">{channels.map(channel => <label key={channel}><input type="checkbox" checked={state.batchChannels.includes(channel)} disabled={state.batchLoading} onChange={event => { setCancelled(false); controller.setBatchChannels(event.target.checked ? [...state.batchChannels, channel] : state.batchChannels.filter(value => value !== channel)); }} />{publicationChannelLabel(channel)}</label>)}</div><p className="wm-small wm-muted">各渠道分别返回结果；检查不会保存、上传或发布内容。</p>{state.batchLoading && <p role="status">正在逐渠道读取准备状态…</p>}{cancelled && <p role="status">已取消读取，可再次检查。</p>}{state.batchError && <p role="alert" className="wm-error">{state.batchError}</p>}{state.batchResult && <ContentBatchResults result={state.batchResult} checked={state.checked} />}</div></Modal></>;
}
