/** Uses the workbench's existing DSH theme; source content is always plain text. */
export const referenceLibraryStyles = `
.wm-workbench .wm-reference-library{width:100%;max-width:1440px;margin:auto;padding:24px;min-width:0}
.wm-ref-heading{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;flex-wrap:wrap;margin-bottom:20px}.wm-ref-heading h2{font-size:25px;letter-spacing:-.035em;margin:5px 0 7px}.wm-ref-heading p{font-size:13px;color:var(--wm-muted);margin:0;max-width:780px}
.wm-ref-collector{border:1px solid var(--wm-border);background:var(--wm-panel);border-radius:14px;padding:18px;margin-bottom:20px}.wm-ref-collector h3{font-size:14px;margin:0 0 12px}
.wm-ref-collector-fields{display:flex;gap:12px;align-items:flex-end;flex-wrap:wrap}.wm-ref-collector-fields label,.wm-ref-filters label{display:grid;gap:5px;font-size:12px;color:var(--wm-muted);min-width:0}
.wm-ref-collector-fields label:first-child{width:160px}.wm-ref-collector-fields .wm-ref-url{flex:1;min-width:240px}.wm-ref-collector-fields .wm-ref-limit{width:112px}.wm-ref-collector-actions{display:flex;gap:8px;flex-wrap:wrap}
.wm-ref-collector input,.wm-ref-collector select,.wm-ref-filters input,.wm-ref-filters select,.wm-ref-assistant textarea{width:100%;min-height:37px;max-width:100%;border:1px solid var(--wm-border);border-radius:9px;background:var(--wm-bg);color:var(--wm-text);padding:7px 11px;font:inherit}
.wm-ref-collector input:disabled,.wm-ref-collector select:disabled{opacity:.65}.wm-ref-hint{font-size:11px;color:var(--wm-muted);margin:11px 0 0}.wm-ref-hint[data-error=true]{color:var(--wm-error)}
.wm-ref-banner{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap;padding:12px 14px;border:1px solid var(--wm-border);border-radius:10px;background:var(--wm-panel);margin:0 0 16px;font-size:13px;overflow-wrap:anywhere}.wm-ref-banner[data-kind=error]{color:var(--wm-error)}.wm-ref-banner p{margin:0}.wm-ref-banner small{font-size:11px;color:var(--wm-muted)}
.wm-ref-filters{display:grid;grid-template-columns:minmax(180px,2fr) repeat(3,minmax(110px,1fr));gap:12px;margin:18px 0 12px}.wm-ref-date-filters{display:flex;gap:12px;align-items:flex-end;flex-wrap:wrap;margin-bottom:16px}.wm-ref-date-filters label{display:grid;gap:5px;color:var(--wm-muted);font-size:12px;min-width:120px}.wm-ref-date-filters input,.wm-ref-date-filters select{max-width:100%;min-height:35px;border:1px solid var(--wm-border);border-radius:8px;background:var(--wm-panel);color:var(--wm-text);padding:6px 9px;font:inherit}
.wm-ref-result-count{font-size:12px;color:var(--wm-muted);margin:0 0 12px}
.wm-ref-items{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,400px),1fr));gap:12px}.wm-ref-item{min-width:0;border:1px solid var(--wm-border);border-radius:12px;background:var(--wm-panel);padding:16px;display:flex;align-items:flex-start;gap:12px;overflow-wrap:anywhere}.wm-ref-item[data-selected=true]{border-color:var(--wm-accent)}
.wm-ref-choice{padding-top:4px;flex:none}.wm-ref-choice input{width:16px;height:16px;accent-color:var(--wm-accent);cursor:pointer}.wm-ref-choice input:disabled{cursor:not-allowed}.wm-ref-item-content{min-width:0;flex:1}
.wm-ref-item-title{border:0;padding:0;background:transparent;color:var(--wm-text);text-align:left;font:inherit;font-size:15px;font-weight:650;line-height:1.55;cursor:pointer;overflow-wrap:anywhere}.wm-ref-item-title:hover{color:var(--wm-accent)}
.wm-ref-item-meta{display:flex;align-items:center;gap:7px;flex-wrap:wrap;font-size:11px;color:var(--wm-muted);margin:8px 0}.wm-ref-badge{display:inline-flex;padding:1px 6px;border:1px solid var(--wm-border);border-radius:5px;font-size:10px}.wm-ref-badge[data-partial=true]{color:var(--wm-warn)}
.wm-ref-excerpt{display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden;white-space:pre-wrap;font-size:12px;color:var(--wm-muted);line-height:1.7;margin:8px 0 11px}.wm-ref-item-footer{display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap;font-size:11px;color:var(--wm-muted)}
.wm-ref-assistant{border:1px solid var(--wm-border);border-radius:13px;background:var(--wm-panel);padding:16px;margin:18px 0}.wm-ref-assistant-head{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}.wm-ref-assistant h3{font-size:14px;margin:0}.wm-ref-agent-actions{display:flex;gap:8px;flex-wrap:wrap}.wm-ref-assistant label{display:block;font-size:12px;color:var(--wm-muted);margin:12px 0 5px}.wm-ref-assistant textarea{resize:vertical;min-height:72px;line-height:1.6}.wm-ref-assistant p{font-size:11px;color:var(--wm-muted);margin:9px 0 0}.wm-ref-assistant .wm-ref-selected-list{display:flex;flex-wrap:wrap;gap:6px;margin:10px 0 0;padding:0;list-style:none}.wm-ref-selected-list li{border:1px solid var(--wm-border);border-radius:6px;padding:3px 7px;max-width:240px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:11px;color:var(--wm-muted)}
.wm-ref-detail-dialog{width:min(900px,calc(100vw - 32px));max-width:100%;overflow-wrap:anywhere}.wm-ref-detail{outline:none;min-width:0}.wm-ref-detail h3{font-size:20px;margin:0 0 12px}.wm-ref-detail-meta{display:flex;gap:9px;flex-wrap:wrap;color:var(--wm-muted);font-size:12px;margin-bottom:15px}.wm-ref-detail-tags{display:flex;gap:6px;flex-wrap:wrap;margin:12px 0}.wm-ref-fulltext{white-space:pre-wrap;overflow-wrap:anywhere;font-size:14px;line-height:1.9;border-top:1px solid var(--wm-border);padding-top:18px;margin:18px 0 0}.wm-ref-detail-media{font-size:12px;color:var(--wm-muted);margin:12px 0}.wm-ref-detail-warning{font-size:12px;color:var(--wm-warn);padding:10px 12px;border:1px solid var(--wm-border);border-radius:9px;margin:12px 0}
/* Native Modal DOM: dialog > content(header, body) + footer. Scope to this
   dialog, using its stable structure instead of generated CSS-module hashes. */
.wm-workbench.wm-ref-detail-dialog{max-height:calc(100vh - 32px);max-height:calc(100dvh - 32px);min-height:0;overflow:hidden}
.wm-workbench.wm-ref-detail-dialog>div:first-child{flex:1 1 auto;min-height:0;overflow:hidden}
.wm-workbench.wm-ref-detail-dialog>div:first-child>div:first-child{flex:none}
.wm-workbench.wm-ref-detail-dialog>div:first-child>div:last-child{flex:1 1 auto;min-height:0;overflow-y:auto;overscroll-behavior:contain;scrollbar-gutter:stable}
.wm-workbench.wm-ref-detail-dialog>div:last-child:not(:first-child){flex:none;flex-wrap:wrap}
.wm-ref-notice{font-size:11px;color:var(--wm-muted);margin-top:18px}
@media(max-width:750px){.wm-workbench .wm-reference-library{padding:16px}.wm-ref-heading h2{font-size:22px}.wm-ref-collector{padding:15px}.wm-ref-collector-fields label:first-child{flex:1;min-width:140px}.wm-ref-collector-fields .wm-ref-url{flex-basis:100%;min-width:0;order:2}.wm-ref-collector-fields .wm-ref-limit{order:1;min-width:90px}.wm-ref-collector-actions{order:3;width:100%}.wm-ref-collector-actions button{flex:1}.wm-ref-filters{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.wm-ref-date-filters label{flex:1;min-width:120px}.wm-ref-item{padding:14px;gap:10px}.wm-ref-assistant-head{align-items:flex-start}.wm-ref-agent-actions{width:100%}.wm-ref-agent-actions button{flex:1;min-width:95px}.wm-ref-detail h3{font-size:18px}}
`;
